PyThon/dateWebapp/dateWebapp/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from dateWebapp import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PyThon/dateWebapp/home/urls.py
from django.urls import path

from home import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name='home'),
    path('login/', views.Login_user.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.Register_user.as_view(), name='register'),
    path('profile/<str:username>', views.Profile.as_view(), name='profile'),
    path('profile/', views.index),
    path('profile/update/avatar', views.Update.as_view(), name='update'),
    path('timkiem/', views.Timkiem.as_view(), name='timkiem'),
    # path('chat/<int:user_2_id>', views.box_chat.as_view(), name='chat'),
    path('chat/api/<int:user_2_id>', views.api_ajax.as_view(), name='api'),
    path('sothich_add/<int:id_st>', views.sothich_add.as_view(), name='sothich_add'),
    path('blog/', views.Post_.as_view(), name='post'),
]

PyThon/dateWebapp/home/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


#
#
# # Create your models here.


class MyUser(AbstractUser):
    avatar = models.FileField(blank=True, null=True)
    diaChi = models.CharField(max_length=1000, blank=True, null=True)
    namSinh = models.DateField(blank=True, null=True)
    gioiTinh = models.CharField(max_length=100, blank=True, null=True)
    intro = models.TextField(blank=True, null=True)


class SoThich(models.Model):
    sothichId = models.AutoField(primary_key=True)
    ten = models.CharField(max_length=100, blank=True, null=True)


class SoThich_User(models.Model):
    user = models.ForeignKey(MyUser, on_delete=models.CASCADE, blank=True, null=False)
    SoThich = models.ForeignKey(SoThich, on_delete=models.CASCADE, blank=True, null=False)


class Conversation(models.Model):
    c_id = models.AutoField(primary_key=True)
    user_1 = models.ForeignKey(MyUser, related_name='user_1', on_delete=models.CASCADE, null=False)
    user_2 = models.ForeignKey(MyUser, related_name='user_2', on_delete=models.CASCADE, null=False)
    created_at = models.DateTimeField(auto_now_add=True)


class Message(models.Model):
    m_id = models.AutoField(primary_key=True)
    from_user = models.ForeignKey(MyUser, on_delete=models.CASCADE, null=False)
    conversation = models.ForeignKey(Conversation, on_delete=models.CASCADE, null=False)
    content = models.TextField(null=False)
    created_at = models.DateTimeField(auto_now_add=True)


class Database:
    def __init__(self, user_id):
        self.userid = str(user_id)

    def lay_thong_tin_voi_username(self, username):
        sql = "SELECT * FROM home_myuser WHERE username = '" + str(username) + "'OR id = '" + str(username) + "'"
        results = MyUser.objects.raw(sql)
        return results

    def lay_thong_tin_all_user(self):
        sql = "SELECT * FROM home_myuser a JOIN home_sothich_user b ON a.id = b.user_id JOIN home_sothich c ON b.SoThich_id = c.soThichId"
        results = MyUser.objects.raw(sql)
        return results

    def id_room(self, user_1, user_2):
        sql = "SELECT c_id FROM home_conversation WHERE user_1_id = '" + str(user_1) + "' AND user_2_id = '" + str(
            user_2) + "' OR user_2_id =  '" + str(user_1) + "' AND user_1_id = '" + str(user_2) + "'"
        kt = Conversation.objects.raw(sql)[:1]
        if kt:
            a = kt[0].c_id
            return a
        else:
            return False

    def context_room_chat(self, id_room):
        sql = "SELECT * FROM home_message WHERE conversation_id = " + str(id_room)
        ketqua = Conversation.objects.raw(sql)
        return ketqua

    def da_tung_chat(self):
        sql = "SELECT * FROM home_myuser WHERE EXISTS (SELECT * FROM home_conversation WHERE user_1_id = " + self.userid + " OR user_2_id  =" + self.userid + ") AND id != " + self.userid
        ketqua = Conversation.objects.raw(sql)
        return ketqua

    def so_thich(self):
        sql = "SELECT * FROM home_sothich"
        ketqua = Conversation.objects.raw(sql)
        return ketqua


    def so_thich_user(self):
        sql = "SELECT * FROM home_sothich_user a JOIN home_sothich b ON a.SoThich_id = b.soThichId"
        ketqua = Conversation.objects.raw(sql)
        return ketqua

class Post(models.Model):
    post_id = models.AutoField(primary_key=True)
    ten = models.TextField(blank=True, null=True)
    link = models.TextField(blank=True, null=True)
    photo = models.FileField(null=True)
    noidung = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.ten

PyThon/dateWebapp/home/views.py
from datetime import date

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from django.shortcuts import render, redirect

# Create your views here.
from django.views import View
from home.models import MyUser, Database, Conversation, Message, SoThich, SoThich_User, Post


def index(request):
    if request.user.is_authenticated:
        database = Database(request.user.id)
        context = {
            'profile': database.lay_thong_tin_all_user(),
            'da_tung_chat': database.da_tung_chat(),
            'sothich': database.so_thich(),
        }
        return render(request, 'home/base.html', context)
    else:
        return render(request, 'home/login.html')


class Login_user(View):
    def get(self, request):
        if request.user.is_authenticated:
            return redirect('home:home')
        else:
            return render(request, 'home/login.html')

    def post(self, request):
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('home:login')
                else:
                    return render(request, 'home/login.html', {'message': 'Tài khoản đã bị vô hiệu hóa'})
            else:
                return render(request, 'home/login.html', {'message': 'Sai  tài khoản hoặc mật khẩu'})


def logout_user(request):
    try:
        logout(request)
    except:
        pass
    return redirect('home:login')


class Register_user(View):
    def get(self, request):
        return render(request, 'home/register.html')

    def post(self, request):
        username = request.POST.get('username')
        email = request.POST.get('email')
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        password = request.POST.get('password')
        password1 = request.POST.get('password1')
        birthday = request.POST.get('birthday')
        gender = request.POST.get('gender')
        address = request.POST.get('address')
        if password != password1:
            return render(request, 'home/register.html', {'message': 'Mật khẩu không trùng nhau'})
        else:
            new_user = MyUser()
            new_user.username = username
            new_user.email = email
            new_user.first_name = first_name
            new_user.last_name = last_name
            new_user.set_password(password)
            new_user.namSinh = birthday
            new_user.gioiTinh = gender
            new_user.diaChi = address
            new_user.save()
            newuser = MyUser.objects.filter(username=username)
            if newuser:
                return redirect('home:login')
            else:
                return render(request, 'home/register.html', {'message': 'Mật khẩu cần có cả chữ và sô'})


class Profile(View):
    def get(self, request, username):
        database = Database(request.user.id)
        context = {
            'profile': database.lay_thong_tin_voi_username(username),
            'da_tung_chat': database.da_tung_chat(),
            'sothich': database.so_thich(),
            'so_thich_user': database.so_thich_user(),
        }
        return render(request, 'home/profile.html', context)


class sothich_add(View):
    def get(self, request, id_st):
        sql = "SELECT * FROM home_sothich_user WHERE SoThich_id = " + str(id_st) + " AND user_id =" + str(
            request.user.id)
        a = SoThich_User.objects.raw(sql)
        if not a:
            user_st = SoThich_User()
            user_st.user = request.user
            user_st.SoThich = SoThich.objects.get(sothichId=id_st)
            user_st.save()
        return redirect('home:home')


class Timkiem(View):
    def post(self, request):
        gender = request.POST.get('gender')
        tuoi_tu = request.POST.get('tuoi_tu')
        tuoi_den = request.POST.get('tuoi_den')
        diachi = request.POST.get('diachi')
        sothich = request.POST.get('sothich')
        last_name = request.POST.get('last_name')
        if tuoi_tu != '':
            today = date.today()
            x = today.year - int(tuoi_tu)
            y = today.year - int(tuoi_den)
            if x < y:
                sql_year = "AND DATE(namSinh) BETWEEN '" + str(x) + "' AND '" + str(y) + "'"
            else:
                sql_year = "AND DATE(namSinh) BETWEEN '" + str(y) + "' AND '" + str(x) + "'"
        else:
            sql_year = ""

        if diachi != '':
            sqldc = "AND a.diaChi like  '%" + str(diachi) + "%' "
        else:
            sqldc = ''

        if sothich != '':
            sql_st = "AND b.SoThich_id like  '%" + str(sothich) + "%' "
        else:
            sql_st = ''
        if last_name != '':
            sql_ln = "AND a.last_name like  '%" + str(last_name) + "%' "
        else:
            sql_ln = ''

        sql = "SELECT * FROM home_myuser a JOIN home_sothich_user b ON a.id = b.user_id WHERE gioiTinh like '%" + str(
            gender) + "%'" + sql_year + sqldc + sql_st + sql_ln + "GROUP BY a.id ORDER BY date_joined DESC"
        results = MyUser.objects.raw(sql)
        database = Database(request.user.id)
        context = {
            'profile': results,
            'da_tung_chat': database.da_tung_chat(),
            'so_thich_user': database.so_thich_user(),
        }
        return render(request, 'home/return_user.html', context)

class Post_(View):
    def get(self, request,post_id):
        sql = "SELECT * From home_post where post_id ='"+str(post_id)+"'"
        post = Post.objects.raw(sql)

        context = {
            'post': post,

        }
        return render(request, 'home/blog.html', context)

class api_ajax(View):
    def get(self, request, user_2_id):
        if request.user.is_authenticated:
            database = Database(request.user.id)
            id_room = database.id_room(request.user.id, user_2_id)
            if not id_room:
                try:
                    Conv = Conversation()
                    Conv.user_1 = MyUser.objects.get(id=request.user.id)
                    Conv.user_2 = MyUser.objects.get(id=user_2_id)
                    Conv.save()
                except:
                    return redirect('home:login')
            ketqua = database.context_room_chat(id_room)
            profile = database.lay_thong_tin_voi_username(user_2_id)
            context = {
                'ketqua': ketqua,
                'profile': profile,
            }
            return render(request, 'home/return_chat.html', context)

        else:
            return redirect('home:login')

    def post(self, request, user_2_id):
        if request.user.is_authenticated:
            database = Database(request.user.id)
            id_room = database.id_room(request.user.id, user_2_id)
            # lưu tin nhắn
            if request.POST.get('content') != '':
                Mess = Message()
                Mess.from_user = MyUser.objects.get(id=request.user.id)
                Mess.conversation = Conversation.objects.get(c_id=id_room)
                Mess.content = request.POST.get('content')
                Mess.save()
            # in ra kết quả
            ketqua = database.context_room_chat(id_room)
            profile = database.lay_thong_tin_voi_username(user_2_id)
            context = {
                'ketqua': ketqua,
                'profile': profile
            }
            return render(request, 'home/return_chat.html', context)

        else:
            return redirect('home:login')


class Update(View):
    def post(self, request):
        if request.user.is_authenticated:
            get_user = MyUser.objects.get(id=request.user.id)
            a = request.POST.get('intro')
            try:
                avatar = request.FILES['avatar']
                get_user.avatar = avatar
            except:
                pass
            get_user.intro = a
            get_user.save()

            return redirect('home:home')
        else:
            return redirect('home:login')

PyThon/dateWebapp/templates/home/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Home{% endblock %}</title>
    <script type="text/javascript" src="https://code.jquery.com/jquery-latest.pack.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'fontawesome-free-5.15.1-web/css/all.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
</head>

<body>
{% if user.is_authenticated %}
    <div class="navbar">
        <img style="display: block; margin-left: auto; margin-right: auto; height: 130px" src="/static/images/logo.png" alt="logo">
        <div class="bar">
            <a href="{% url 'home:home' %}"> <i class="fas fa-home "></i> <span> Home</span> </a>
            <a href="{% url 'home:profile' user.username %}"><i class="fas fa-user"></i> Profile</a>
            <a href="{% url 'home:post' %}"><i class="fas fa-blog"></i> Blogs</a>
            <a href="{% url 'home:logout' %}"><i class="fas fa-sign-out-alt"></i> Log out</a>
        </div>
    </div>
{% endif %}

<div id="flex_row">
    {% block  content %}
        <div class="bar">
            <div id="filter">
                <input type="text" id="last_name" placeholder="Name">

                {% csrf_token %}
                <select id="gender">
                    <option value="">Gender</option>
                    <option value="nam">Male</option>
                    <option value="nu">Female</option>
                </select>
                <input type="number" id="tuoi_tu" min="18" max="60" placeholder="Age from">
                <input type="number" id="tuoi_den" min="18" max="60" placeholder="Age to">
                <input type="text" id="diachi" placeholder="Enter an address">
                <select id="sothich">
                    <option value="">Hobby</option>
                    {% for i in sothich %}
                        <option value="{{ i.sothichId }}">{{ i.ten }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="block_card" id="results"></div>
        <div id="results"></div>
        <script>
            setInterval(function () {
                $.ajax({
                    type: "POST",
                    url: "{% url 'home:timkiem'%}",
                    data: {
                        'gender': $('#gender').val(),
                        'tuoi_tu': $('#tuoi_tu').val(),
                        'tuoi_den': $('#tuoi_den').val(),
                        'diachi': $('#diachi').val(),
                        'sothich': $('#sothich').val(),
                        'last_name': $('#last_name').val(),
                        'csrfmiddlewaretoken': $("input[name=csrfmiddlewaretoken]").val()
                    },
                    dataType: 'html',
                    success: function (data) {
                        $('#results').html(data)
                    },
                });
            }, 500);
            setTimeout(function () {
                $.ajax({
                    type: "POST",
                    url: "{% url 'home:timkiem'%}",
                    data: {
                        'gender': $('#gender').val(),
                        'tuoi_tu': $('#tuoi_tu').val(),
                        'tuoi_den': $('#tuoi_den').val(),
                        'diachi': $('#diachi').val(),
                        'sothich': $('#sothich').val(),
                        'csrfmiddlewaretoken': $("input[name=csrfmiddlewaretoken]").val()
                    },
                    dataType: 'html',
                    success: function (data) {
                        $('#results').html(data)
                    },
                });
            }, 0);
        </script>
    {% endblock %}

</div>

{% if user.is_authenticated %}
    <div class="bar">
        <a href="{% url 'home:home' %}"> <i class="fas fa-home "></i> <span> Home</span> </a>
        <a href="{% url 'home:profile' user.username %}"><i class="fas fa-user"></i> Profile</a>
        <a href=""><i class="fas fa-blog"></i> Blogs</a>
        <a href="{% url 'home:logout' %}"><i class="fas fa-sign-out-alt"></i> Log out</a>
    </div>
{% endif %}
</body>
</html>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
        crossorigin="anonymous"></script>
<script type="text/javascript" src="https://code.jquery.com/jquery-latest.pack.js"></script>

PyThon/dateWebapp/templates/home/blog.html
{% extends 'home/base.html' %}
{% block title %}Blogs{% endblock %}
{% block content %}
    <div class="Baiviet">
        AAAAAAAAAAAAAAAAAAAAA
    </div>
{% endblock %}

PyThon/dateWebapp/templates/home/index.html
{% extends 'home/base.html' %}
{% block title %}{% endblock %}
{% block content %}
    <div class="sticky__">
        <div id="filter">
            {% csrf_token %}
            <select id="gender">
                <option value="">Giới Tính</option>
                <option value="nam">Nam</option>
                <option value="nu">Nữ</option>
            </select>
            <input type="number" id="tuoi_tu" min="18" max="60" placeholder="Tuổi từ">
            <input type="number" id="tuoi_den" min="18" max="60" placeholder="Tuổi đến">
            <input type="text" id="diachi" placeholder="Nhập  địa chỉ" required>
            <input type="text" id="sothich" placeholder="Nhập Sở Thích" required>
        </div>
    </div>
    <hr>
    <div class="block_card" id="results"></div>
    <script>
        setInterval(function () {
            $.ajax({
                type: "POST",
                url: "{% url 'home:timkiem'%}",
                data: {
                    'gender': $('#gender').val(),
                    'tuoi_tu': $('#tuoi_tu').val(),
                    'tuoi_den': $('#tuoi_den').val(),
                    'diachi': $('#diachi').val(),
                    'sothich': $('#sothich').val(),
                    'csrfmiddlewaretoken': $("input[name=csrfmiddlewaretoken]").val()
                },
                dataType: 'html',
                success: function (data) {
                    $('#results').html(data)
                },
            });
        }, 1000);
        setTimeout(function () {
            $.ajax({
                type: "POST",
                url: "{% url 'home:timkiem'%}",
                data: {
                    'gender': $('#gender').val(),
                    'tuoi_tu': $('#tuoi_tu').val(),
                    'tuoi_den': $('#tuoi_den').val(),
                    'diachi': $('#diachi').val(),
                    'sothich': $('#sothich').val(),
                    'csrfmiddlewaretoken': $("input[name=csrfmiddlewaretoken]").val()
                },
                dataType: 'html',
                success: function (data) {
                    $('#results').html(data)
                },
            });
        }, 0);
    </script>
{% endblock %}

PyThon/dateWebapp/templates/home/login.html
{% extends 'home/base.html' %}
{% block title %}Log In{% endblock %}
{% block content %}
    <div class="base_content">

        <img style="width: 100%; height: 250px;" src="/static/images/logo.png" alt="logo">
        <div class="container">
            <div class="bar_login">
                <div class="log"><a href="{% url 'home:login' %}">Log In</a></div>
                <div>&</div>
                <div class="log"><a href="{% url 'home:register' %}">Register</a></div>
            </div>
            <div class="col-md-12">
                <form action="{% url  'home:login' %}" method="post">
                    {% csrf_token %}
                    <div class="form--group">
                        <label for="username">Username or Email address</label>
                        <input type="text" class="form-control" id="username" name="username"
                               placeholder="username">
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input type="password" class="form-control" id="password" name="password"
                               placeholder="password">
                    </div>
                    <small class="form-text text-muted"> {{ message }}</small>
                    <hr class="mb-4">
                    <button type="submit" class="btn-grad">LOGIN</button>
                </form>
            </div>
        </div>

    </div>
{% endblock %}

PyThon/dateWebapp/templates/home/profile.html
{% extends 'home/base.html' %}
{% load static %}
{% block title %}Profile{% endblock %}
{% block content %}
    <div class="profile">
        <div class="infor">
            {% for item in profile %}
                {% if item.avatar %}
                    <img class="avatar_profile" src="{{ item.avatar.url }}"
                         alt="avatar">
                {% else %}
                    <img class="avatar_profile" src="{% static 'images/avatar.jpeg' %}"
                         alt="avatar">
                {% endif %}
                <div class="profile_name">
                    <a href="{% url 'home:profile' item.username %}"> {{ item.first_name }} {{ item.last_name }}</a>
                    {% if item.gioiTinh ==  'nam' or item.gioiTinh ==  'Nam' %}
                        <i class="fas fa-mars" style="font-size: 25px;color:#015b81;"></i>
                    {% else %}
                        <i class="fas fa-venus" style="font-size: 25px;color:#c406bb;"></i>
                    {% endif %}
                </div>
                <div class="profile_body">
                    <div>
                        <span><i class="fas fa-birthday-cake"></i>&emsp;{{ item.namSinh }}</span>
                        <span><i class="fas fa-map-marked-alt"></i>&emsp;{{ item.diaChi }}</span>
                    </div>
                    <div class="intro"><i class="fas fa-pen-alt"></i>   {{ item.intro }}</div>
                    <span>Hobbies:</span>
                    <span style="padding-left: 10px;">
                        {% for i_ in so_thich_user %}
                            {% if item.id == i_.user_id %}
                                {{ i_.ten }}<br>
                            {% endif %}
                        {% endfor %}
                    </span>
                </div>


            {% endfor %}

            <br>
            {% if user.username == profile.0.username %}

                <form class="in_form" action="{% url 'home:update' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <label for="avatar">Avatar:</label>
                    <input type="file" id="avatar" accept='image/*' name="avatar"> <br>
                    <label for="intro">Intro:</label>
                    <textarea type="" id="intro" value="{{ profile.0.intro }}" name="intro" placeholder="introduction"></textarea>
                    <br>
                    <input class="btn-grad" type="submit" value="submit" style="width: 30%;padding: 5px;text-transform: capitalize;" >
                </form>


                <hr><p>Thêm các sở thích để được đề xuất nhiều hơn :</p>
                <div>
                    {% for i in sothich %}
                        <button class="st_bt"><a href="{% url 'home:sothich_add' i.sothichId %}">{{ i.ten }}</a></button>
                    {% endfor %}
                </div>



            {% endif %}

        </div>
        <div class="boxchat">
            <div id="results-message" class="chat_window_content">
            </div>
            {% csrf_token %}
            {% if user.username == profile.0.username %}
                <input type="text" id="content_chat" class="chat_input"
                       placeholder="Gửi tín nhắn cho chính bạn" required>
            {% else %}
                <input type="text" id="content_chat" class="chat_input"
                       placeholder="Nhập tin nhắn muốn gửi..." required>
            {% endif %}
        </div>
    </div>
    <script>
        $('#content_chat').click(function () {
            $('#results-message').scrollTop($('#results-message')[0].scrollHeight);
        });

        $('#content_chat').keypress(function (e) {
            if (e.which === 13) {
                $.ajax({
                    type: "POST",
                    url: "{% url 'home:api' profile.0.id %}",
                    data: {
                        'content': $('#content_chat').val(),
                        'csrfmiddlewaretoken': $("input[name=csrfmiddlewaretoken]").val()
                    },
                    dataType: 'html',
                    success: function (data) {
                        $('#content_chat').val('');
                        $('#results-message').html(data)
                    },
                });
            }
        });

        setInterval(function () {
            $.ajax({
                type: "GET",
                url: "{% url 'home:api' profile.0.id %}",
                dataType: 'html',
                success: function (data) {
                    $('#results-message').html(data);

                },
            });
        }, 1000);
        setTimeout(function () {
            $.ajax({
                type: "GET",
                url: "{% url 'home:api' profile.0.id %}",
                dataType: 'html',
                success: function (data) {
                    $('#results-message').html(data);
                    $('#results-message').scrollTop($('#results-message{{ item.id }}')[0].scrollHeight);
                },
            });
        }, 0);
    </script>
{% endblock %}

PyThon/dateWebapp/templates/home/register.html
{% extends 'home/base.html' %}
{% block title %}Register{% endblock %}
{% block content %}
    <div class="base_content">
        <img style="width: 100%; height: 250px;" src="/static/images/logo.png" alt="logo">
        <div class="container">

        <div class="bar_login">
            <div><a href="{% url 'home:login' %}">Log In</a></div>
            <div>&</div>
            <div><a href="{% url 'home:register' %}">Register</a></div>
        </div>
        <div class="col-md-12">
            <form class="needs-validation" action="{% url  'home:register' %}" method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-6 mb-3">
                        <label for="firstName">First name</label>
                        <input type="text" class="form-control" id="firstName" name="first_name"
                               placeholder="Enter your first name" required>
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="lastName">Last name</label>
                        <input type="text" class="form-control" id="lastName" name="last_name"
                               placeholder="Enter your last name" required=>
                    </div>
                </div>
                <div class="mb-3">
                    <label for="username">Username</label>
                    <div class="input-group">

                        <input type="text" class="form-control" id="username" name="username"
                               placeholder="Enter your account name" required>
                    </div>
                </div>

                <div class="mb-3">
                    <label for="email">Email </label>
                    <input type="email" class="form-control" id="email" name="email" placeholder="Enter your email address"
                           required>
                </div>
                <div class="mb-3">
                    <label for="address">Address</label>
                    <input type="text" class="form-control" id="address" name="address" placeholder="Enter an address"
                           required>
                </div>
                <div class="row">
                    <div class="col-md-6 mb-3">
                        <label for="country">Gender</label>
                        <select class="custom-select d-block w-100" id="country" name="gender" required="">
                            <option value="">Choose...</option>
                            <option value="nam">Male</option>
                            <option value="nu">Female</option>
                        </select>
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="birthday">Date of Birth</label>
                        <input type="date" class="form-control" id="birthday" name="birthday" required>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 mb-3">
                        <label for="password">Password</label>
                        <input type="password" class="form-control" id="password" name="password"
                               placeholder="Enter password" required>
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="password1">Repeat Password</label>
                        <input type="password" class="form-control" id="password1" name="password1"
                               placeholder="Repeat Password" required>
                    </div>
                </div>
                {% if message %}
                    <small class="form-text text-muted"> {{ message }}</small>
                {% endif %}
                <hr class="mb-4">
                <button class="btn-grad" type="submit">Register</button>
            </form>
        </div>
    </div>
    </div>
{% endblock %}