PyThon/Loc/Loc/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PyThon/Loc/home/urls.py
from django.urls import path
from home import views

app_name = 'home'
urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('login/', views.Login_user.as_view(), name='login'),
    path('register/', views.Register_user.as_view(), name='register'),
    path('logout/', views.logout_user, name='logout'),
    path('newpost/', views.DangBai.as_view(), name='newpost'),
    path('profile/<str:username>', views.Profile.as_view(), name='profile'),
    path('search/', views.Search.as_view(), name='search'),
    path('edit_profile/', views.Edit_profile.as_view(), name='edit_profile'),
    path('comments/<int:post_id>', views.comment_post, name='comments'),

]

PyThon/Loc/home/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.
class MyUser(AbstractUser):
    avatar = models.FileField(blank=True, null=True)
    namSinh = models.DateField(blank=True, null=True)
    gioiTinh = models.CharField(max_length=100, blank=True, null=True)


class Follower(models.Model):
    f_id = models.AutoField(primary_key=True)
    main_user = models.ForeignKey(MyUser(id), related_name='main_user', on_delete=models.CASCADE, null=False)
    user_fl = models.ForeignKey(MyUser(id), related_name='user_fl', on_delete=models.CASCADE, null=False)
    created_at = models.DateTimeField(auto_now_add=True)


class Post(models.Model):
    post = models.AutoField(primary_key=True)
    user = models.ForeignKey(MyUser(id), on_delete=models.CASCADE, blank=True, null=False)
    content = models.TextField(blank=True, null=True)
    photo = models.FileField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)


class Comment(models.Model):
    comment = models.AutoField(primary_key=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, blank=False, null=False)
    user = models.ForeignKey(MyUser(id), on_delete=models.CASCADE, blank=False, null=False)
    content = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)


class Tim(models.Model):
    tim_id = models.AutoField(primary_key=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, blank=False, null=False)
    user = models.ForeignKey(MyUser(id), on_delete=models.CASCADE, blank=False, null=False)

PyThon/Loc/home/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect

# Create your views here.
from django.views import View

from home.models import MyUser, Post, Comment


class Index(View):
    def get(self, request):
        if request.user.is_authenticated:
            sql = "SELECT * FROM home_post a JOIN home_myuser b ON a.user_id = b.id ORDER BY created_at DESC "
            home_post = Post.objects.raw(sql)
            context = {
                'home_post': home_post
            }

            return render(request, 'home/feed.html', context)
        else:
            return redirect('home:login')

class Register_user(View):
    def get(self, request):
        return render(request, 'home/register.html')

    def post(self, request):
        username = request.POST.get('username')
        email = request.POST.get('email')
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        password = request.POST.get('password')
        password1 = request.POST.get('password1')
        birthday = request.POST.get('birthday')
        gender = request.POST.get('gender')
        if password != password1:
            return render(request, 'home/register.html', {'message': 'Mật khẩu không trùng nhau'})
        else:
            new_user = MyUser()
            new_user.username = username
            new_user.email = email
            new_user.first_name = first_name
            new_user.last_name = last_name
            new_user.set_password(password)
            new_user.namSinh = birthday
            new_user.gioiTinh = gender
            new_user.save()
            newuser = MyUser.objects.filter(username=username)
            if newuser:
                return redirect('home:login')
            else:
                return render(request, 'home/register.html', {'message': 'Mật khẩu cần có cả chữ và sô'})


class Login_user(View):
    def get(self, request):
        if request.user.is_authenticated:
            return redirect('home:index')
        else:
            return render(request, 'home/login.html')

    def post(self, request):
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('home:login')
            else:
                return render(request, 'home/login.html', {'message': 'Tài khoản đã bị vô hiệu hóa'})
        else:
            return render(request, 'home/login.html', {'message': 'Sai  tài khoản hoặc mật khẩu'})


def logout_user(request):
    try:
        logout(request)
    except:
        pass
    return redirect('home:login')


class DangBai(View):
    def get(self, request):
        if request.user.is_authenticated:
            return render(request, 'home/newpost.html')
        else:
            return redirect('home:login')

    def post(self, request):
        content = request.POST.get('content')
        photo = request.FILES['photo']
        get_user = MyUser.objects.get(id=request.user.id)
        newpost = Post()
        newpost.content = content
        newpost.photo = photo
        newpost.user = get_user
        newpost.save()
        return redirect('home:index')


class Profile(View):
    def get(self, request, username):
        if request.user.is_authenticated:
            sql_user = "SELECT * FROM home_myuser WHERE username ='" + str(username) + "'"
            user = MyUser.objects.raw(sql_user)
            sql_post = "SELECT * FROM home_post a JOIN home_myuser b ON a.user_id = b.id  WHERE username ='" + str(
                username) + "' ORDER BY created_at DESC "
            user_post = Post.objects.raw(sql_post)
            context = {
                'user_profile': user,
                'user_post': user_post
            }
            return render(request, 'home/profile.html', context)
        else:
            return redirect('home:login')


class Search(View):
    def post(self, request):
        if request.user.is_authenticated:
            key = request.POST.get('key')
            sqldc = " WHERE username like  '" + str(key) + "%' "
            sql_user = "SELECT * FROM home_myuser " + sqldc
            user = MyUser.objects.raw(sql_user)
            context = {
                'user_': user,
            }
            return render(request, 'home/explore.html', context)
        else:
            return redirect('home:login')


class Edit_profile(View):
    def get(self, request):
        if request.user.is_authenticated:
            sql_user = "SELECT * FROM home_myuser WHERE username ='" + str(request.user.username) + "'"
            user = MyUser.objects.raw(sql_user)
            context = {
                'user_profile': user,
            }
            return render(request, 'home/edit-profile.html', context)
        else:
            return redirect('home:login')

    def post(self, request):
        if request.user.is_authenticated:
            get_user = MyUser.objects.get(username=request.user.username)
            get_user.first_name = request.POST.get('first_name')
            get_user.last_name = request.POST.get('last_name')
            get_user.email = request.POST.get('email')
            get_user.namSinh = request.POST.get('namSinh')
            get_user.gioiTinh = request.POST.get('gender')
            try:
                get_user.avatar = request.FILES['avatar']
            except:
                pass
            get_user.save()
            sql_user = "SELECT * FROM home_myuser WHERE username ='" + str(request.user.username) + "'"
            user = MyUser.objects.raw(sql_user)
            context = {
                'user_profile': user,
                'mess': "Thành Công",
            }
            return render(request, 'home/edit-profile.html', context)
        else:
            return redirect('home:login')

def comment_post(request, post_id):
    if request.user.is_authenticated:
        if request.method == 'POST':
            content = request.POST.get('content')
            if content != '':
                new_cm = Comment()
                new_cm.content = content
                new_cm.user_id = request.user.id
                new_cm.post_id = post_id
                new_cm.save()

        sql_comments = "SELECT * FROM home_comment a JOIN home_myuser b ON  a.user_id = b.id WHERE a.post_id =" + str(
            post_id)
        post_comment = Post.objects.raw(sql_comments)
        context = {
            'post_comment': post_comment,
        }
        return render(request, 'home/ajax_cmt.html', context)

    else:
        return redirect('home:login')

PyThon/Loc/templates/home/ajax_cmt.html
{% for item  in post_comment %}
    <li class="photo__comment">
        <span class="photo__comment-author">{{ item.username }}</span>{{ item.content }}
    </li>
{% endfor %}

PyThon/Loc/templates/home/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Feed | Instaclone</title>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="shortcut icon" href="../../static/home/images/favicon.ico" type="image/x-icon">
    <link href="../../static/home/css/style.css" rel="stylesheet">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script type="text/javascript" src="https://code.jquery.com/jquery-latest.pack.js"></script>

</head>
<body>
<nav class="navigation">
    <a href="{% url  'home:index' %}">
        <img
                src="../../static/home/images/navLogo.png"
                alt="logo"
                title="logo"
                class="navigation__logo"
        />
    </a>
    <div class="navigation__search-container">
        <i class="fa fa-search"></i>
        {% csrf_token %}
        <input type="text" id="key" value="" placeholder="Search">
    </div>
    <script>
        $('#key').change(function () {
            $.ajax({
                type: "POST",
                url: "{% url 'home:search'%}",
                data: {
                    'key': $('#key').val(),
                    'csrfmiddlewaretoken': $("input[name=csrfmiddlewaretoken]").val()
                },
                dataType: 'html',
                success: function (data) {
                    $('#content_').html(data)
                },
            });
        });


    </script>

    <div class="navigation__icons">
        <a href="{% url 'home:logout' %}" class="navigation__link">
            đăng xuất
        </a>
        <a href="{% url 'home:newpost' %}" class="navigation__link">
            đăng bài
        </a>
        <a href="explore.html" class="navigation__link">
            <i class="fa fa-compass"></i>
        </a>
        <a href="#" class="navigation__link">
            <i class="fa fa-heart-o"></i>
        </a>
        <a href="{% url 'home:profile' user.username %}" class="navigation__link">
            <i class="fa fa-user-o"></i>
        </a>
    </div>
</nav>
<div id="content_">
    {% block content %}
    {% endblock content %}
</div>


<footer class="footer">
    <nav class="footer__nav">
        <ul class="footer__list">
            <li class="footer__list-item"><a href="#" class="footer__link">about us</a></li>
            <li class="footer__list-item"><a href="#" class="footer__link">support</a></li>
            <li class="footer__list-item"><a href="#" class="footer__link">blog</a></li>
            <li class="footer__list-item"><a href="#" class="footer__link">press</a></li>
            <li class="footer__list-item"><a href="#" class="footer__link">api</a></li>
            <li class="footer__list-item"><a href="#" class="footer__link">jobs</a></li>
            <li class="footer__list-item"><a href="#" class="footer__link">privacy</a></li>
            <li class="footer__list-item"><a href="#" class="footer__link">terms</a></li>
            <li class="footer__list-item"><a href="#" class="footer__link">directory</a></li>
            <li class="footer__list-item"><a href="#" class="footer__link">language</a></li>
        </ul>
    </nav>
    <span class="footer__copyright">© 2017 instagram</span>
</footer>
<script
        src="https://code.jquery.com/jquery-3.2.1.min.js"
        integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
        crossorigin="anonymous"></script>
<script src="../../static/home/js/app.js"></script>
</body>
</html>
<script type="text/javascript" src="https://code.jquery.com/jquery-latest.pack.js"></script>

PyThon/Loc/templates/home/edit-profile.html
{% extends 'home/base.html' %}
{% block content %}
    <main class="edit-profile">
        {% for item in user_profile %}
            <section class="profile-form">
                <header class="profile-form__header">
                    <div class="profile-form__avatar-container">
                        {% if item.avatar %}
                        <img
                                src="{{ item.avatar.url }}"
                                class="profile-form__avatar"
                        />
                        {% else %}
                         <img
                                src=""
                                class="profile-form__avatar"
                        />
                        {% endif %}
                    </div>
                    <h4 class="profile-form__title">{{ item.username }}</h4>
                </header>
                <form action="{% url 'home:edit_profile' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="edit-profile__form-row">
                        <label for="first_name" class="edit-profile__label">first_name
                        </label>
                        <input id="first_name" name="first_name" type="text" value="{{ item.first_name }}"
                               class="edit-profile__input"/>
                    </div>
                    <div class="edit-profile__form-row">
                        <label for="last_name" class="edit-profile__label">last_name
                        </label>
                        <input id="last_name" name="last_name" type="text" value="{{ item.last_name }}"
                               class="edit-profile__input"/>
                    </div>
                    <div class="edit-profile__form-row">
                        <label for="email" class="edit-profile__label"> Email </label>
                        <input type="email" class="edit-profile__input" name="email" id="email" value="{{ item.email }}"/>
                    </div> <div class="edit-profile__form-row">
                        <label for="namSinh" class="edit-profile__label"> namSinh </label>
                        <input type="date" class="edit-profile__input" value="{{ item.namSinh|date:'Y-m-d'  }}" name="namSinh" id="namSinh"/>
                    </div>

                    <div class="edit-profile__form-row">
                        <label for="gender" class="edit-profile__label">Gender</label>
                        <select id="gender" name="gender">
                            <option value="male">Male</option>
                            <option value="female">Female</option>
                            <option value="whatever">Whatever</option>
                        </select>
                    </div>
                    <label for="avatar">Ảnh đại diện</label>
                    <input type="file" id="avatar" accept='image/*' name="avatar">
                    <div class="edit-profile__form-row">
                        <label class="edit-profile__label"></label>
                        <input type="submit" value="Submit">
                    </div>
                    {{ mess }}
                </form>
            </section>
        {% endfor %}
    </main>
{% endblock %}

PyThon/Loc/templates/home/explore.html
{% load static %}
<main class="explore">
    <section class="people">
        <ul class="people__list">
            {% for item_ in user_ %}
                <li class="people__person">
                    <div class="people__column">
                        <div class="people__avatar-container">
                            {%   if item_.avatar %}
                            <img
                                    src="{{ item_.avatar.url }}"
                                    class="people__avatar"
                            />
                            {% else %}
                             <img
                                    src="{% static 'home/images/feedPhoto.jpg' %}"
                                    class="people__avatar"
                            />
                            {% endif %}
                        </div>
                        <div class="people__info">
                            <span class="people__username">{{ item_.username }}</span>
                            <span class="people__full-name">{{ item_.first_name }} {{ item_.last_name }}</span>
                        </div>
                    </div>
                    <div class="people__column">
                        <a href="#">Follow</a>
                    </div>
                </li>
            {% endfor %}
        </ul>
    </section>
</main>

PyThon/Loc/templates/home/feed.html
{% extends 'home/base.html' %}
{% block content %}
    <main class="feed">
        {% for post in home_post %}
            <section class="photo">
                <header class="photo__header">
                    <div class="photo__header-column">
                        <img
                                class="photo__avatar"
                                src="media/{{ post.avatar }}"
                        />
                    </div>
                    <div class="photo__header-column">
                        <span class="photo__username">{{ post.first_name }} {{ post.last_name }}</span>

                    </div>
                </header>
                <div class="photo__file-container">
                    <img
                            class="photo__file"
                            src="{{ post.photo.url }}"
                    />
                </div>
                <div class="photo__info">
                    <div class="photo__icons">
                        <span class="photo__icon">
                            <i class="fa fa-heart-o heart fa-lg"></i>
                        </span>
                        <span class="photo__icon">
                            <i class="fa fa-comment-o fa-lg"></i>
                        </span>
                    </div>
                    <span class="photo__likes">35 likes</span>
                    <ul class="photo__comments">
                        <li class="photo__comment">
                            <span class="photo__comment-author">{{ post.first_name }} {{ post.last_name }}</span>{{ post.content }}
                        </li>
                        <div id="results-comment{{ post.post }}">

                        </div>

                    </ul>
                    <span class="photo__time-ago">{{ post.created_at }}</span>
                    <div class="photo__add-comment-container">
                        {% csrf_token %}
                        <input type="text" placeholder="Add a comment..." name="content" id="content{{ post.post }}"
                                  class="photo__add-comment">
                        <i class="fa fa-ellipsis-h"></i>
                    </div>
                </div>
                <script>
                    $('#content{{ post.post }}').keypress(function (e) {
                        if (e.which === 13) {
                            $.ajax({
                            type: "POST",
                            url: "{% url 'home:comments'  post.post %}",
                            data: {
                                'content': $('#content{{ post.post }}').val(),
                                'csrfmiddlewaretoken': $("input[name=csrfmiddlewaretoken]").val()
                            },
                            dataType: 'html',
                            success: function (data) {
                                $('#content{{ post.post }}').val('');
                                $('#results-comment{{ post.post }}').html(data)
                            },
                        });
                        }
                    });
                    function load_comments() {
                        $.ajax({
                            type: "GET",
                            url: "{% url 'home:comments' post.post %}",
                            dataType: 'html',
                            success: function (data) {
                                $('#results-comment{{ post.post }}').html(data)
                            },
                        });
                    }

                    setTimeout(load_comments, 0);
                    setInterval(load_comments, 1000);
                </script>

            </section>
        {% endfor %}
    </main>
{% endblock %}

PyThon/Loc/templates/home/login.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Login | Instaclone</title>
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
        <link rel="shortcut icon" href="../../static/home/images/favicon.ico" type="image/x-icon">
        <link href="../../static/home/css/style.css" rel="stylesheet">
        <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    </head>
    <body class="no-padding">
        <main class="login">
            <div class="login__column">
                <img 
                    src="../../static/home/images/phone.png"
                    alt="Phone Image"
                    title="Phone Image"
                    class="login__phone-image"
                />                
            </div>
            <section class="login__column">
                <div class="login__section login__sign-in">
                    <img 
                        src="../../static/home/images/logo.png"
                        alt="Logo"
                        title="Logo"
                        class="login__logo"
                    />
                    <!-- x   -->
                    <form method="POST" action="{% url 'home:login' %}" class="login__form">
                        {% csrf_token %}
                        <div class="login__input-container">
                            <input 
                                type="text"
                                name="username"
                                placeholder="Username"
                                required
                                class="login__input"
                            />
                        </div>
                        <div class="login__input-container">
                            <input 
                                type="password"
                                name="password"
                                placeholder="Password"
                                required
                                class="login__input" 
                            />
                            <a href="#" class="login__form-link">Forgot?</a>
                        </div>
                        <div class="login__input-container">
                            <input
                                type="submit"
                                value="Log in"
                                class="login__input login__input--btn"
                            />
                        </div>
                    </form>
                    <span class="login__divider">or</span>
                    <a class="login__fb-link" href="#">
                        <i class="fa fa-facebook-square fa-lg" aria-hidden="true"></i> Log in with Facebook
                    </a>
                </div>
                <div class="login__section login__sign-up">
                    <span class="login__text">
                        Don't have an account? 
                        <a href="{% url 'home:register' %}" class="login__link">
                            Sign up
                        </a>
                    </span>
                </div>
                <div class="login__section login__section--transparent login__app">
                    <span class="login__text">
                        Get the app.
                    </span>
                    <div class="login__appstores">
                        <img 
                            src="../../static/home/images/ios.png"
                            alt="iOS"
                            title="Get the app!"
                            class="login__appstore" 
                        />
                        <img 
                            src="../../static/home/images/android.png"
                            alt="Android"
                            title="Get the app!"
                            class="login__appstore" 
                        />
                    </div>
                </div>
            </section>
        </main>
        <footer class="footer">
            <nav class="footer__nav">
                <ul class="footer__list">
                    <li class="footer__list-item"><a href="#" class="footer__link">about us</a></li>
                    <li class="footer__list-item"><a href="#" class="footer__link">support</a></li>
                    <li class="footer__list-item"><a href="#" class="footer__link">blog</a></li>
                    <li class="footer__list-item"><a href="#" class="footer__link">press</a></li>
                    <li class="footer__list-item"><a href="#" class="footer__link">api</a></li>
                    <li class="footer__list-item"><a href="#" class="footer__link">jobs</a></li>
                    <li class="footer__list-item"><a href="#" class="footer__link">privacy</a></li>
                    <li class="footer__list-item"><a href="#" class="footer__link">terms</a></li>
                    <li class="footer__list-item"><a href="#" class="footer__link">directory</a></li>
                    <li class="footer__list-item"><a href="#" class="footer__link">language</a></li>
                </ul>
            </nav>
            <span class="footer__copyright">© 2017 instagram</span>
        </footer>
        <script
  src="https://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous"></script>
        <script src="../../static/home/js/app.js"></script>
    </body>
</html>

PyThon/Loc/templates/home/newpost.html
{% extends 'home/base.html' %}
{% block content %}
    <form action="{% url 'home:newpost' %}" method="post" class="container" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-3">
            <textarea class="form-control" name="content" id="exampleFormControlTextarea1" rows="3" required></textarea>
        </div>
        <input type="file" accept='image/*' name="photo" required>
        <input type="submit" value="submit">
    </form>
{% endblock %}

PyThon/Loc/templates/home/profile.html
{% extends 'home/base.html' %}
{% block content %}
    <main class="profile-container">
        <section class="profile">
            <header class="profile__header">
                {% for user in  user_profile %}
                    <div id="avatar" class="profile__avatar-container">
                        {% if user.avatar %}

                        <img src="{{ user.avatar.url }}" class="profile__avatar"/>
                        {% else %}
                             <img src="" class="profile__avatar"/>
                    {% endif %}
                    </div>
                    <div class="profile__info">
                        <div class="profile__name">
                            <h1 class="profile__title">{{ user.first_name }} {{ user.last_name }}</h1>
                            <a href="{% url 'home:edit_profile' %}" class="profile__button u-fat-text">Edit profile</a>
                            <i class="fa fa-cog fa-2x" id="cog"></i>
                        </div>
                        <ul class="profile__numbers">
                            <li class="profile__posts">
                                <span class="profile__number u-fat-text">10</span> posts
                            </li>
                            <li class="profile__followers">
                                <span class="profile__number u-fat-text">40</span> followers
                            </li>
                            <li class="profile__following">
                                <span class="profile__number u-fat-text">134</span> following
                            </li>
                        </ul>
                    </div>

                {% endfor %}

            </header>
            <div class="profile__pictures">
                {% for post in user_post %}
                <a href="image-detail.html" class="profile-picture">
                    <img
                            src="{{ post.photo.url }}"
                            class="profile-picture__picture"
                    />
                    <div class="profile-picture__overlay">
                            <span class="profile-picture__number">
                                <i class="fa fa-heart"></i> 450
                            </span>
                        <span class="profile-picture__number">
                                <i class="fa fa-comment"></i> 39
                            </span>
                    </div>
                </a>
              {% endfor %}
            </div>
        </section>
    </main>
{% endblock %}