PyThon/Tww/Tww/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('homepage.urls')), #  thêm đường dẫn url cho app homepage
    path('',include('music.urls')), 
]

PyThon/Tww/homepage/urls.py
from django.urls.conf import path
from . import views

app_name  = 'homepage'

urlpatterns = [
    path('', views.index,  name= 'index'),  # tạo đường dẫn  đến hàm login trong view.py
    path('login', views.MyLogin,  name=  'login'),  # tạo đường dẫn  đến hàm login trong view.py
    path('logout', views.MyLogout, name = 'logout'),
    path('register', views.MyRegister, name = 'register'),
]

PyThon/Tww/music/urls.py
from django.urls import path
from music import views

app_name ='music'
urlpatterns =[
    path('add/album',views.AddAlbum, name = 'addalbum'),
    path('delete/album/<int:id>',views.DeleteAlbum, name = 'deletealbum'),
    path('edit/album/<int:id>',views.EditAlbum, name = 'editalbum'),
]

PyThon/Tww/homepage/models.py
from django.db import models

# Create your models here.

PyThon/Tww/music/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

# Tạo album
class Album(models.Model):
    albumId = models.AutoField(primary_key=True)
    title = models.CharField(max_length  = 250, blank = True, null = True)
    detail = models.CharField(max_length  = 1000, blank = True, null = True)
    logo = models.CharField(max_length = 250, blank = True, null = True)
    star = models.CharField(max_length = 250, blank = True, null = True)
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING,blank = True, null = True)  # Người tạo Album

    def __str__(self):
        return self.title

class Song(models.Model):
    songId = models.AutoField(primary_key = True)
    albumId = models.ForeignKey(Album,on_delete=models.DO_NOTHING, blank = True, null = True)
    songName = models.CharField(max_length = 250, blank = True, null = True)
    audio =  models.CharField(max_length = 250, blank = True, null = True)
    star = models.CharField(max_length = 250, blank = True, null = True)

PyThon/Tww/homepage/views.py
from django.contrib.auth.models import User
from django.shortcuts import redirect, render
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.hashers import make_password
from music.models import Album


# Create your views here.
def index(request):
    if request.user.is_authenticated:
        albums = Album.objects.filter(user=request.user)
        user= request.user        
        context = {
            'albums': albums,
            'user': user
        }
        return render(request,'homepage/index.html',context)
    else:
        return redirect('homepage:login')




def MyLogin(request):
    if request.user.is_authenticated:
        return redirect('homepage:index')
    else:
        if request.method == 'POST':
            # Lấy username và password 
            username = request.POST.get('username')
            password = request.POST.get('password')
            # kiểm tra xem username và password có trong dữ liệu hay không
            user = authenticate(username = username, password = password)
            if user is not None: # Nếu tìm thấy user có userName và password đã nhập
                if user.is_active:  #  Tài khoản có bị vô hiệu hóa hay không
                    login(request,user)
                    # trả  về trang index
                    # Lấy tất cả album của user đã đăng nhập
                    albums = Album.objects.filter(user=request.user)
                    return render(request,'homepage/index.html',{'albums':albums})
                else:
                    return render(request,'homepage/login.html',{'message':'Tài khoản đã bị vô hiệu hóa'})
            else:
                return render(request,'homepage/login.html',{'message':'Tài khoản không tồn tại'})
        return render(request,'homepage/login.html')
    

def MyLogout(request):
    # nếu không có tài khoản nào thì không thực hiện đăng xuất
    try:
        logout(request)
    except:
        pass
    # nếu đăng xuất thành công thì trả về trang đăng nhập
    return redirect('homepage:login')

    
def MyRegister(request):
    # Nếu đã đăng nhập thì trả về index
    if request.user.is_authenticated:
        return redirect('homepage:index')
    else:
        if request.method =='POST':
            username = request.POST.get('username')
            password1 = request.POST.get('password1')
            password2 = request.POST.get('password2')
            if username == '' or password1 == ''or password2 =='' or password1 != password2:
                return  render(request,'homepage/register.html',{'message':'Sai gì đó'})
            else:
                new_user = User()
                new_user.username  = username
                new_user.set_password(password1)
                new_user.save()
                user = authenticate(username = username, password = password1)
                login(request, user,backend='django.contrib.auth.backends.ModelBackend')
                return redirect('homepage:index')

    return render(request,'homepage/register.html')

PyThon/Tww/music/views.py
from django.shortcuts import redirect, render
from music.models import *

# Create your views here.
def AddAlbum(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            title = request.POST.get('title')
            detail = request.POST.get('detail') 
            star = request.POST.get('star')
            logo = request.POST.get('logo')
            if title ==  '' or star == '' or logo == '':
                return render(request,'music/add_album.html')
            else:
                new_album = Album()
                new_album.title = title
                new_album.detail = detail
                new_album.star = star
                new_album.logo = logo
                new_album.user = request.user
                new_album.save()
                return redirect('homepage:index')
        
        return render(request,'music/add_album.html')
    else:
        return redirect('homepage:login')

def DeleteAlbum(request,id):
    if request.user.is_authenticated:        
        get_album = Album.objects.get(albumId=id)
        get_album.delete() 
        return redirect('homepage:index')
    else:
        return redirect('homepage:login')

def EditAlbum(request,id):
    if request.user.is_authenticated:    
        get_album = Album.objects.get(albumId=id)   
        if request.method == 'POST':
            title = request.POST.get('title') 
            detail = request.POST.get('detail') 
            star = request.POST.get('star')
            logo = request.POST.get('logo')
            get_album.title = title
            get_album.detail = detail
            get_album.star = star
            get_album.logo = logo
            get_album.save()
            return redirect('homepage:index')          
        context ={
            'album':get_album,
        }
        
        return render(request,'music/edit_album.html',context)
    else:
        return redirect('homepage:login')       

PyThon/Tww/homepage/templates/homepage/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/png" href="{% static 'homepage/images/icons/favicon.ico'%}"/>
    <title>Home</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'homepage:index' %}">TW</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
          <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'music:addalbum' %}">Thêm Album<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Xin chào ,{{user.first_name}} {{user.last_name}} ({{user.username}})</a>
              </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'homepage:logout' %}">Đăng Xuất</a>
            </li>            
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
    </nav>
    
    <div style="margin-top: 40px; display: flex;    
    flex-flow: row wrap;
    justify-content: space-around;
    align-content: space-around;">
        {% for album in albums %}
            <div class="card mb-3" style="max-width: 540px;">
                <div class="row no-gutters">
                <div class="col-md-4">
                    {% if album.logo != None %}
                        <img class="card-img" alt="..." src="{{album.logo}}">
                    {% else %}
                        <img class="card-img" alt="..." src="https://cdn.pixabay.com/photo/2016/11/29/01/22/album-1866523__340.jpg">
                    {% endif %}
                    <hr>                    
                    &nbsp; &nbsp;&nbsp; &nbsp;    
                    <a  href="{% url 'music:editalbum' album.albumId %}"> <i class="fas fa-edit"></i>Sửa</a> &nbsp; &nbsp;
                    <a  href="{% url 'music:deletealbum' album.albumId %}"><i class="fas fa-trash-alt"></i>Xóa</a> 
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                    <h5 class="card-title">{{album.title}}</h5>
                    {% if album.detail != None %}
                        <p class="card-text">{{album.detail}}</p>  
                    {% else %}
                        <p class="card-text">Ablum hiện chưa có phần giới thiệu</p>  
                    {% endif %}



                    <p class="card-text"><small class="text-muted">Đánh giá: {{album.star}}/5 <i style="color:rgb(22, 113, 155)" class="fas fa-star"></i></small></p>
                    <p class="card-text"><small class="text-muted">Thuộc về {{user.first_name}} {{user.last_name}} ({{user.username}})</small></p>   
                    </div>
                </div>
                </div>
            </div>
            {% endfor %}    
    </div>
</body>
</html>

PyThon/Tww/homepage/templates/homepage/login.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	{% load static %}
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="{% static 'homepage/images/icons/favicon.ico'%}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'homepage/vendor/bootstrap/css/bootstrap.min.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'homepage/fonts/font-awesome-4.7.0/css/font-awesome.min.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'homepage/fonts/Linearicons-Free-v1.0.0/icon-font.min.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'homepage/vendor/animate/animate.css'%}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'homepage/vendor/css-hamburgers/hamburgers.min.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'homepage/vendor/animsition/css/animsition.min.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'homepage/vendor/select2/select2.min.css'%}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'homepage/vendor/daterangepicker/daterangepicker.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'homepage/css/util.css'%}">
	<link rel="stylesheet" type="text/css" href="{% static 'homepage/css/main.css'%}">
<!--===============================================================================================-->
</head>
<body>
	
	<div class="limiter">
		<div class="container-login100" style="background-image: url('{% static 'homepage/images/bg-01.jpg' %}')">
			<div class="wrap-login100 p-l-110 p-r-110 p-t-62 p-b-33">
				<form class="login100-form validate-form flex-sb flex-w"  enctype="multipart/form-data" method="post">
					{% csrf_token %}
					<span class="login100-form-title p-b-53">
						Sign In With
					</span>

					<a href="#" class="btn-face m-b-20">
						<i class="fa fa-facebook-official"></i>
						Facebook
					</a>

					<a href="#" class="btn-google m-b-20">
						<img src="{% static 'homepage/images/icons/icon-google.png'%}" alt="GOOGLE">
						Google
					</a>
					
					<div class="p-t-31 p-b-9">
						<span class="txt1">
							Username
						</span>
					</div>
					<div class="wrap-input100 validate-input" data-validate = "Username is required">
						<input class="input100" type="text" name="username" >
						<span class="focus-input100"></span>
					</div>
					
					<div class="p-t-13 p-b-9">
						<span class="txt1">
							Password
						</span>

						<a href="#" class="txt2 bo1 m-l-5">
							Forgot?
						</a>
					</div>
					<div class="wrap-input100 validate-input" data-validate = "Password is required">
						<input class="input100" type="password" name="password" >
						<span class="focus-input100"></span>
					</div>
					{% if message  %}
						<div style="margin-top:10px">{{message}}</div>						
					{% endif %}
					<div class="container-login100-form-btn m-t-17">
						<button class="login100-form-btn">
							Sign In
						</button>
					</div>

					<div class="w-full text-center p-t-55">
						<span class="txt2">
							Not a member?
						</span>

						<a href="{% url 'homepage:register' %}" class="txt2 bo1">
							Sign up now
						</a>
					</div>
				</form>
			</div>
		</div>
	</div>
	

	<div id="dropDownSelect1"></div>
	
<!--===============================================================================================-->
	<script src="{% static 'homepage/vendor/jquery/jquery-3.2.1.min.js'%}"></script>
<!--===============================================================================================-->
	<script src="{% static 'homepage/vendor/animsition/js/animsition.min.js'%}"></script>
<!--===============================================================================================-->
	<script src="{% static 'homepage/vendor/bootstrap/js/popper.js'%}"></script>
	<script src="{% static 'homepage/vendor/bootstrap/js/bootstrap.min.js'%}"></script>
<!--===============================================================================================-->
	<script src="{% static 'homepage/vendor/select2/select2.min.js'%}"></script>
<!--===============================================================================================-->
	<script src="{% static 'homepage/vendor/daterangepicker/moment.min.js'%}"></script>
	<script src="{% static 'homepage/vendor/daterangepicker/daterangepicker.js'%}"></script>
<!--===============================================================================================-->
	<script src="{% static 'homepage/vendor/countdowntime/countdowntime.js'%}"></script>
<!--===============================================================================================-->
	<script src="{% static 'homepage/js/main.js'%}"></script>

</body>
</html>

PyThon/Tww/homepage/templates/homepage/login2.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Login</title>
	<style>
		input{
			margin: 10px;
		}
	</style>
</head>
<body>
	{% if message  %}
		{{message}}
	{% endif %}
	<form action="" enctype="multipart/form-data" method="post">

		{% csrf_token %}
		<label for="username">User Name</label>
		<input id = "username" type="text" name="username">
		<br>
		<label for="password">Password</label>
		<input id = "password" type="password" name = "password">
		<br>
		<input type="submit" value="Đăng nhập">
	</form>
</body>
</html>

PyThon/Tww/homepage/templates/homepage/register.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Đăng kí</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	{% load static %}
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="{% static 'homepage/images/icons/favicon.ico'%}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'homepage/vendor/bootstrap/css/bootstrap.min.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'homepage/fonts/font-awesome-4.7.0/css/font-awesome.min.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'homepage/fonts/Linearicons-Free-v1.0.0/icon-font.min.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'homepage/vendor/animate/animate.css'%}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'homepage/vendor/css-hamburgers/hamburgers.min.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'homepage/vendor/animsition/css/animsition.min.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'homepage/vendor/select2/select2.min.css'%}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'homepage/vendor/daterangepicker/daterangepicker.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'homepage/css/util.css'%}">
	<link rel="stylesheet" type="text/css" href="{% static 'homepage/css/main.css'%}">
<!--===============================================================================================-->
</head>
<body>
	
	<div class="limiter">
		<div class="container-login100" style="background-image: url('{% static 'homepage/images/bg-01.jpg' %}')">
			<div class="wrap-login100 p-l-110 p-r-110 p-t-62 p-b-33">
				<form class="login100-form validate-form flex-sb flex-w"  enctype="multipart/form-data" method="post">
					{% csrf_token %}
					<span class="login100-form-title p-b-53">
						Đăng Kí
					</span>			
					
					<div class="p-t-31 p-b-9">
						<span class="txt1">
							Username
						</span>
					</div>
					<div class="wrap-input100 validate-input" data-validate = "Username is required">
						<input class="input100" type="text" name="username" >
						<span class="focus-input100"></span>
					</div>
					
					<div class="p-t-13 p-b-9">
						<span class="txt1">
							Password
						</span>
                    </div>
                    <div class="wrap-input100 validate-input" data-validate = "Password is required">
						<input class="input100" type="password" name="password1" >
						<span class="focus-input100"></span>
					</div>
                    <div class="p-t-13 p-b-9">
						<span class="txt1">
							Nhập lại Password
						</span>						
					</div>
					<div class="wrap-input100 validate-input" data-validate = "Password is required">
						<input class="input100" type="password" name="password2" >
						<span class="focus-input100"></span>
					</div>
					{% if message  %}
						<div style="margin-top:10px">{{message}}</div>						
					{% endif %}				
					<div class="container-login100-form-btn m-t-17">
						<button class="login100-form-btn">
							Đăng Kí 
						</button>
					</div>

					<div class="w-full text-center p-t-55">						
						<a href="{% url 'homepage:login' %}" class="txt2 bo1">
							Sign in
						</a>
					</div>
				</form>
			</div>
		</div>
	</div>
	

	<div id="dropDownSelect1"></div>
	
<!--===============================================================================================-->
	<script src="{% static 'homepage/vendor/jquery/jquery-3.2.1.min.js'%}"></script>
<!--===============================================================================================-->
	<script src="{% static 'homepage/vendor/animsition/js/animsition.min.js'%}"></script>
<!--===============================================================================================-->
	<script src="{% static 'homepage/vendor/bootstrap/js/popper.js'%}"></script>
	<script src="{% static 'homepage/vendor/bootstrap/js/bootstrap.min.js'%}"></script>
<!--===============================================================================================-->
	<script src="{% static 'homepage/vendor/select2/select2.min.js'%}"></script>
<!--===============================================================================================-->
	<script src="{% static 'homepage/vendor/daterangepicker/moment.min.js'%}"></script>
	<script src="{% static 'homepage/vendor/daterangepicker/daterangepicker.js'%}"></script>
<!--===============================================================================================-->
	<script src="{% static 'homepage/vendor/countdowntime/countdowntime.js'%}"></script>
<!--===============================================================================================-->
	<script src="{% static 'homepage/js/main.js'%}"></script>

</body>
</html>

PyThon/Tww/music/templates/music/add_album.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Thêm Album</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	{% load static %}
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="{% static 'homepage/images/icons/favicon.ico'%}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'homepage/vendor/bootstrap/css/bootstrap.min.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'homepage/fonts/font-awesome-4.7.0/css/font-awesome.min.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'homepage/fonts/Linearicons-Free-v1.0.0/icon-font.min.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'homepage/vendor/animate/animate.css'%}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'homepage/vendor/css-hamburgers/hamburgers.min.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'homepage/vendor/animsition/css/animsition.min.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'homepage/vendor/select2/select2.min.css'%}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'homepage/vendor/daterangepicker/daterangepicker.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'homepage/css/util.css'%}">
	<link rel="stylesheet" type="text/css" href="{% static 'homepage/css/main.css'%}">
<!--===============================================================================================-->
</head>
<body>
	
	<div class="limiter">
		<div class="container-login100" style="background-image: url('{% static 'homepage/images/bg-01.jpg' %}')">
			<div class="wrap-login100 p-l-110 p-r-110 p-t-62 p-b-33">
				<form class="login100-form validate-form flex-sb flex-w"  enctype="multipart/form-data" method="post">
					{% csrf_token %}
					<span class="login100-form-title p-b-53">
						Thêm album
					</span>			
					
					<div class="p-t-31 p-b-9">
						<span class="txt1">
							Tên Album
						</span>
					</div>
					<div class="wrap-input100 validate-input" data-validate = "Username is required">
						<input class="input100" type="text" name="title" >
						<span class="focus-input100"></span>
					</div>

					<div class="p-t-31 p-b-9">
						<span class="txt1">
							Giới thiệu
						</span>
					</div>
					<div class="wrap-input100 validate-input" data-validate = "Username is required">
						<input class="input100" type="text" name="detail" >
						<span class="focus-input100"></span>
					</div>
					
					<div class="p-t-13 p-b-9">
						<span class="txt1">
							Số ngôi sao
						</span>
                    </div>
                    <div class="wrap-input100 validate-input" data-validate = "Password is required">
						<input class="input100" type="text" name="star" >
						<span class="focus-input100"></span>
					</div>
                    <div class="p-t-13 p-b-9">
						<span class="txt1">
							Logo
						</span>						
					</div>
					<div class="wrap-input100 validate-input" data-validate = "Password is required">
						<input class="input100" type="text" name="logo" >
						<span class="focus-input100"></span>
					</div>
					{% if message  %}
						<div style="margin-top:10px">{{message}}</div>						
					{% endif %}
					<div class="container-login100-form-btn m-t-17">
						<button class="login100-form-btn">
							Thêm album 
						</button>
					</div>

					<div class="w-full text-center p-t-55">						
						<a href="{% url 'homepage:index' %}" class="txt2 bo1">
							Trở Lại
						</a>
					</div>
				</form>
			</div>
		</div>
	</div>
	

	<div id="dropDownSelect1"></div>
	
<!--===============================================================================================-->
	<script src="{% static 'homepage/vendor/jquery/jquery-3.2.1.min.js'%}"></script>
<!--===============================================================================================-->
	<script src="{% static 'homepage/vendor/animsition/js/animsition.min.js'%}"></script>
<!--===============================================================================================-->
	<script src="{% static 'homepage/vendor/bootstrap/js/popper.js'%}"></script>
	<script src="{% static 'homepage/vendor/bootstrap/js/bootstrap.min.js'%}"></script>
<!--===============================================================================================-->
	<script src="{% static 'homepage/vendor/select2/select2.min.js'%}"></script>
<!--===============================================================================================-->
	<script src="{% static 'homepage/vendor/daterangepicker/moment.min.js'%}"></script>
	<script src="{% static 'homepage/vendor/daterangepicker/daterangepicker.js'%}"></script>
<!--===============================================================================================-->
	<script src="{% static 'homepage/vendor/countdowntime/countdowntime.js'%}"></script>
<!--===============================================================================================-->
	<script src="{% static 'homepage/js/main.js'%}"></script>

</body>
</html>